def warning():
    return f'\nWARNING\n<<FILES CAN BE PERMANENTLY DELETED AND ALSO CANT BE RECOVERED>>\n'
def help():
    return f'INSTRUCTIONS:\n1.MAKE A DIRECTORY AND PLACE THE FILES AND FOLDERS THAT YOU WANT TO DELETE IN THAT DIRECTORY,WE WOULD RECOMMEND YOU NOT TO CREATE THE DIRECTORY IN C DRIVE\n2.COPY THE PATH TO THAT DIRECTORY\n3.PASTE THAT PATH AS INPUT\n4.FILES OR FOLDERS MUST BE PERMITTED TO READ,WRITE,MODIFY AND ALSO NOT BE HIDDEN\n5.Unable_to_shred DIRECTORY CONTAINS THE FILES AND FOLDERS THAT CAN NOT BE OVERWRITTEN NOR DELETED BY THIS PROGRAM\n'